### ISSUE TITLE
Unable to enter Password; Window closes on trying

### ISSUE THREAD

**Issue by aquaritus** [e-alfred/ocDownloader_webextension#6]
When I try to enter my account data from my nextcloud instance, I can only enter the URL and my username. As soon as I switch to Password, the windows closes. 
I'm using Firefox 61.0.1 on Ubuntu.
Could reproduce the error on two different installations.

**Comment by e-alfred** [comment]
I know this issue, it is a bug caused by a package Firefox depends on Ubuntu (ibus-gtk3). It also happens with other extensions like Floccus and many more.

Here is the upstream bug: https://github.com/ibus/ibus/issues/2002 and https://bugzilla.mozilla.org/show_bug.cgi?id=1451466

A workaround is to either install the Snap version of Firefox or try this workaround: https://github.com/subdavis/Tusk/issues/146#issuecomment-392568013

Another workaround is to install an updated ibus-gtk3 package from here: https://bugzilla.mozilla.org/show_bug.cgi?id=1405634#c16

**Comment by aquaritus** [comment]
Thanks for your answer. The workaround worked for me. Unfortunately  the Youtube-dl funcion doesn't work. I added a comment on the corresponding issue.

**Comment by e-alfred** [comment]
This should be fixed by Ubuntu/Gnome/Ibus/Firefox now.
